# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d343124ae00eedff7d6c49f409ecd3c1b70db317817e540206b8dca257362524a5debc266ae5bb859013416c328ada35afef09f692735611becc4e7be79b4e45

test:
  secret_key_base: dbcad06f7aa0c00ac4c57b2e90549d079478465b91ded3adfc9c43200292b3c2707f919c394fa68e295a83e43373d22366c7d0e99bc4a6f06cb6ee0c95901fa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
